// ThreeFiveMiniUfloat — port of tsvm_core/src/net/torvald/tsvm/ThreeFiveMinifloat.kt.
// 3.5 unsigned minifloat (3-bit exponent + 5-bit mantissa) scaled so the smallest
// non-zero step is 1/256 s ≈ 3.91 ms and the max is 15.75 s. Used for Taud
// envelope point offsets.
//
// The LUT is generated by the minifloat formula (e = i>>5, m = i&31;
// denormal e=0 → m/256, else (32+m)·2^(e−1)/256) — values are exact binary
// fractions, so this reproduces the Kotlin float LUT bit-exactly.

export const MINIFLOAT_LUT = new Float32Array(256);
for (let i = 0; i < 256; i++) {
  const e = i >> 5;
  const m = i & 31;
  MINIFLOAT_LUT[i] = e === 0 ? m / 256 : ((32 + m) * 2 ** (e - 1)) / 256;
}

export function minifloatToDouble(index) {
  return MINIFLOAT_LUT[index & 0xff];
}

// fromFloatToIndex (ThreeFiveMinifloat.kt:24-27): binary-search the interval,
// then "round to nearest even" — if the lower bound index is even take it,
// else take the upper bound. Ported verbatim, quirk included.
export function minifloatFromDouble(fval) {
  let low = 0;
  let high = MINIFLOAT_LUT.length - 1;
  let llim, hlim;
  for (;;) {
    if (low > high) {
      llim = Math.max(high, 0);
      hlim = Math.min(low, MINIFLOAT_LUT.length - 1);
      break;
    }
    const mid = (low + high) >>> 1;
    const midVal = MINIFLOAT_LUT[mid];
    if (fval < midVal) high = mid - 1;
    else if (fval > midVal) low = mid + 1;
    else { llim = mid; hlim = mid; break; }
  }
  return llim % 2 === 0 ? llim : hlim;
}
